.github/workflows/tests.yaml
Scrolling through tons of garbage gets old fast.
=> Reduce verbosity of pip install step in CI

.github/workflows/asan.yaml, .github/workflows/clang_tidy.yaml, .github/workflows/docs.yaml, .github/workflows/pypi_publish.yml, .github/workflows/test_bazel.yaml, .github/workflows/test_conda_env.yaml, .github/workflows/tests.yaml, CMakeLists.txt, README.md, docker/Dockerfile, pyproject.toml, src/vmecpp/cpp/util/hdf5_io/hdf5_io.h, src/vmecpp/cpp/util/testing/numerical_comparison_lib.cc, src/vmecpp/cpp/util/testing/numerical_comparison_lib.h, src/vmecpp/cpp/vmecpp/vmec/output_quantities/output_quantities.cc
Download dependencies during build using Cmake FetchContent instead of having them checked into the repo as submodules. resolves https://github.com/proximafusion/vmecpp/issues/124
=> replaced submodules with FetchContent calls

src/vmecpp/simsopt_compat.py
This fixes #174. I'll add a regression test in the next PR.
=> Fix path comparison in simsopt_compat.py

src/vmecpp/__about__.py, src/vmecpp/cpp/MODULE.bazel
We need a new release for the fix to #147.
=> Bump VMEC++ version to v0.2.0

tests/test_simsopt_compat.py
=> In test_simsopt_compat, also test with Fortran inputs

tests/test_simsopt_compat.py
It's a 3/4x speed-up in test runtime.
=> Reuse VMEC++ run in test_simsopt_compat

.github/workflows/asan.yaml, .github/workflows/docs.yaml, .github/workflows/pypi_publish.yml, .github/workflows/test_bazel.yaml, .github/workflows/tests.yaml, CMakeLists.txt, README.md, pyproject.toml, src/vmecpp/__init__.py, src/vmecpp/cpp/vmecpp/common/flow_control/BUILD.bazel, src/vmecpp/cpp/vmecpp/common/flow_control/flow_control.cc, src/vmecpp/cpp/vmecpp/common/flow_control/flow_control.h, src/vmecpp/cpp/vmecpp/vmec/radial_profiles/BUILD.bazel, src/vmecpp/cpp/vmecpp/vmec/radial_profiles/radial_profiles.cc, src/vmecpp/simsopt_compat.py, tests/test_init.py
- Prevent segfault due to out of bounds array access when passing 0 or negative thread count
- Prevent segfault when passing >1 threads when compiled w/o openmp
- Avoid the transitive include of Abseil Check https://google.github.io/styleguide/cppguide.html#Include_What_You_Use
=> without OpenMP max threads should always be one

.github/workflows/tests.yaml
Doesn't do much at the moment, but ensures correctness as we add more examples to the doc-strings.
=> Add doctest to CI

src/vmecpp/cpp/vmecpp/common/vmec_indata/vmec_indata.cc
Optimize JSON output for boundary geometry by only including non-zero values and asymmetric components when needed.
- Modified the `ToJson()` method in `VmecINDATA` class to only include non-zero values in the boundary geometry arrays (`rbc`, `zbs`, `rbs`, `zbc`)
- Introduced a lambda function `push_nonzero` to handle the common logic of only adding non-zero values to the output
The fields `raxis_c` and `zaxis_s` already follow this "Optional field" convention, and it seems that rbs and zbc were also intended this way.
=> Only write rbs, zbc when lasym to be consistent with r_axis, z_axis

src/vmecpp/simsopt_compat.py
There were subtle differences in deserialization logic, due to the diverging implementation. This reconciles the two.
=> Remove duplicate deserialization logic in simsopt_compat.Vmec

src/vmecpp/__init__.py
the `from_wout_file` method iterated through the keys of `VmecWOut` and read each one from the `netcdf` file. This had the skips keys which are present in the netcdf file, but not our VmecWOut file. 
We already have a list of quantities where we expect the two to differ, so why not use that instead? 
The result is a tighter contract, since the Pydantic model complains about both missing and extra keys.
**This helped me identify a few mismatches between Fortran wout and our Pydantic model, which were added to the missing variables.**
=> from_wout_file Iterate through present keys instead of expected keys

pyproject.toml
Removes large test files from published wheels
=> Remove mgrid test files from wheels

tests/test_init.py
Becomes relevant for checking extcur quantities
=> [WOut] Test failed for scalar comparison nan==nan, although it is a valid value

src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.cc, src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.h, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc
- Rename `MGridProvider::loadFromMGrid` to `MGridProvider::LoadFile` as per TODO
Already updated function signature in test: https://github.com/proximafusion/vmecpp_large_cpp_tests/commit/29b2f1666cd65c2e75a2db05f732b7ec55bb66bb
=> Rename loadFromMgrid to LoadFile

.github/workflows/test_conda_env.yaml, .github/workflows/tests.yaml, src/vmecpp/__init__.py, src/vmecpp/cpp/vmecpp/vmec/output_quantities/output_quantities.cc, src/vmecpp/cpp/vmecpp/vmec/output_quantities/output_quantities.h, src/vmecpp/cpp/vmecpp/vmec/output_quantities/output_quantities_test.cc, src/vmecpp/cpp/vmecpp/vmec/pybind11/pybind_vmec.cc, tests/cpp/vmecpp/simsopt_compat/test_fortran_wout_adapter.py
Migration of  https://github.com/proximafusion/repo/pull/15570 by @jons-pf 
Additional fixes:
- Correct nan comparison
- Fixed array dimensions for some quantities
- tighter test cases
=> [WOut] Migrate output quantities bdotb, nextcur added

src/vmecpp/__init__.py
> [!NOTE]
> This PR doesn't change any operational logic, only order of variables and dimension names in wout 
- Rename dimensions to be exactly like VMEC2000 (Some codes, i.e. HINT depend on the exact dimension names)
- Adjust the order of variables to better match VMEC2000, and make diffs between them clearer.
=> [WOut] Tracking down subtle compatibility issues

src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.cc, src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.h, src/vmecpp/cpp/vmecpp/vmec/pybind11/pybind_vmec.cc, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc
- absl::status instead of int return codes, important for better error handling from Python
=> Move from int return values to absl::status

src/vmecpp/cpp/vmecpp/common/flow_control/flow_control.cc, src/vmecpp/cpp/vmecpp/common/flow_control/flow_control.h, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc
**This does not change anything logically**
0 based indexing is easier to reason about in a C++ codebase.
Adjusted all lines referencing `igrid`
=> [flow control] igrid replace 1 based with 0 based indexing

src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.h
**This does not change anything logically**
Trying to make reasoning about the flow control easier.
- Reduced scope of liter_flag
- removed checks that were always true
- added some comments
=> [flow control] Comments and refactored if statements

src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc
**This does not change anything logically**
Getting rid of some shared variables and slowly transforming the loop logic towards something more reminiscent of a for loop
=> [flow control] Thread local iter2 counter

src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc
Turned a while loop into a for loop, whats the big deal?
In very rare cases,  optimizations didn't terminate, possibly because VMEC would continuously reset without increasing the iter2 counter. 
-> Refactored to a simpler for loop, ensuring that the iteration count is always updated when entering, to avoid an infinite loop.
>[!NOTE]
This subtley changes the meaning of niter compared to the original implementation. **Now it counts all evaluations of the forward model, not just the successful ones.** 
----------------
**Now the entire control flow consists of two nested for loops with a max iteration count, will definitely terminate.**
=> [flow control] while->for loop

src/vmecpp/_pydantic_numpy.py, tests/test_pydantic_numpy.py
In 3.13
```py
issubclass(typing.Annotated, str)
Traceback (most recent call last):
File "<python-input-3>", line 1, in <module>
issubclass(typing.Annotated, str)
~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
>>> isinstance(typing.Annotated, type)
False
```
In 3.10
```py
>>> issubclass(typing.Annotated, str)
False
>>> isinstance(typing.Annotated, type)
True
```
This broke our handling of Annotated types.
=> Fixed Py3.13 pydantic serialization

src/vmecpp/__init__.py, tests/test_init.py
Preliminary work to enable generic wout writing
=> Renamed dimension names to be closer to wout convention

AGENTS.md, VMECPP_NAMING_GUIDE.md, docs/fourier_basis_implementation.md, src/vmecpp/cpp/vmecpp/common/fourier_basis_fast_poloidal/fourier_basis_fast_poloidal.h, src/vmecpp/cpp/vmecpp/common/fourier_basis_fast_toroidal/fourier_basis_fast_toroidal.h
=> Document the converter functions between different Fourier basis representations.

examples/python_api_input.py, src/vmecpp/__init__.py, tests/test_init.py
- populate VmecInput fields with explicit defaults
- verify Python defaults match C++ defaults in tests
=> Fix VmecInput default values

README.md, docs/README.md, docs/conf.py, docs/examples_overview.md, docs/index.md, src/vmecpp/__init__.py
- Added examples and fourier basis 
- run and VmecInput show up at the top instead of JxBout
- Made sure latex and code blocks are rendered correctly 
- Make sure the example plot shows up in the online docs (relative filepath issue) <img width="918" height="687" alt="image" src="https://github.com/user-attachments/assets/e1bf487b-ed9a-4dea-b6b9-adadfb420910" />
=> Improved Sphinx docs (Cleaned up docstrings and config)
