src/vmecpp/__about__.py, src/vmecpp/cpp/MODULE.bazel
To align it with the latest git tag and what we
advertise from the MODULE.bazel.
=> Bump version of Python package to 0.1

tests/__init__.py
VMEC++ reports niter == 2 after a run that actually
only performs one iteration with this output:
```
NS = 51   NO. FOURIER MODES = 59   FTOLV = 1.000e-06   NITER = 60000
ITER |    FSQR     FSQZ     FSQL    |    fsqr     fsqz      fsql   |   DELT   |  RAX(v=0) |    W_MHD   |   <BETA>   |  <M>
------+------------------------------+------------------------------+----------+-----------+------------+------------+-------
1 | 9.96e-07  1.35e-07  4.69e-09 | 9.35e-12  2.49e-12  9.85e-11 | 5.00e-01 | 8.789e-01 | 4.4971e-02 | 0.0000e+00 | 1.379
MHD Energy = 4.497072e-02
NUMBER OF JACOBIAN RESETS = 0
```
We might want to fix the niter behavior independently, this commit
is a quick fix for the broken test.
The reason we did not notice is that these tests do not actually
run in the CI (fixed in the …
=> Fix assertion in hot restart test

.gitmodules
So there is no need for ssh credentials to clone the VMEC++ repo.
Thanks to @rogeriojorge for the suggestion.
=> Use https instead of ssh for git submodule URLs

CMakeLists.txt
This automatically, significantly speeds up
`pip install .` runs when the C++ sources have
not changed.
=> Teach CMake to use ccache if available

CMakeLists.txt, README.md, src/vmecpp/cpp/vmecpp/free_boundary/laplace_solver/BUILD.bazel, src/vmecpp/cpp/vmecpp/free_boundary/laplace_solver/laplace_solver.cc, src/vmecpp/cpp/vmecpp/free_boundary/laplace_solver/laplace_solver.h
This removes the use of lapacke which is not standard across all LAPACK vendors. This enables building on macOS without home-brew.
=> Remove lapacke dependency.

docker/Dockerfile
In case it's useful: a few small things to make the `Dockerfile` build for me locally:
- clone the public github repo rather than the private one (so no `GITHUB_TOKEN` needed for that part) (I'm assuming `jons-pf/vmecpp` is the private one and the `proximafusion/vmecpp` is the new public one)
- also recursively clone the submodules
- add a few Debian dependencies that seemed missing
After this the `docker build -t ghcr.io/jons-pf/vmecpp:latest  .` completed for me (although I don't know how to test it properly!)
```
PS C:\Users\dave\github.com\djs55\vmecpp\docker> docker build -t ghcr.io/jons-pf/vmecpp:latest  .
[+] Building 249.4s (10/10) FINISHED                                                               docker:desktop-linux
=> [internal] load build definition from Dockerfile …
```
=> fix docker/Dockerfile

src/vmecpp/_util.py, src/vmecpp/simsopt_compat.py, tests/test_simsopt_compat.py, tests/test_util.py
Before this patch, when multiple processes called
ensure_vmecpp_input on the same input file,
each process would create and then try to delete
the same temporary VMEC++ input file.
With this patch, ensure_vmecpp_input adds the PID
to the name of the temporary input file, removing
the race condition.
=> Fix race condition in ensure_vmecpp_input

.github/workflows/asan.yaml
Add Adress sanitization to the CI. Triggers on push to main or when PR is ready, but not as a cron job, as I do not expect as much activity in this repository as in the internal repo. 
Closes https://github.com/proximafusion/vmecpp/issues/116
Thread sanitization is a different issue mentioned by @jons-pf , and will be handled in a different PR
=> adress sanitization as part of CI

pyproject.toml
- Syncronize  the versions we build wheels for with the versions in .toml
- Add MAC support
- Jax >0.5.0 causes a circular dependency on some systems. Pin for now
=> Updated Python and OS versions for packaging

src/vmecpp/cpp/vmecpp/common/composed_types_lib/composed_types_lib_test.cc, src/vmecpp/cpp/vmecpp/common/flow_control/flow_control.h, src/vmecpp/cpp/vmecpp/common/fourier_basis_fast_poloidal/fourier_basis_fast_poloidal.cc, src/vmecpp/cpp/vmecpp/common/fourier_basis_fast_toroidal/fourier_basis_fast_toroidal.cc, src/vmecpp/cpp/vmecpp/common/magnetic_configuration_definition/magnetic_configuration.h, src/vmecpp/cpp/vmecpp/common/magnetic_configuration_lib/magnetic_configuration_lib.cc, src/vmecpp/cpp/vmecpp/common/util/util.h, src/vmecpp/cpp/vmecpp/common/vmec_indata/vmec_indata.h, src/vmecpp/cpp/vmecpp/free_boundary/tangential_partitioning/tangential_partitioning.cc, src/vmecpp/cpp/vmecpp/free_boundary/tangential_partitioning/tangential_partitioning.h, src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.cc, src/vmecpp/cpp/vmecpp/vmec/profile_parameterization_data/profile_parameterization_data.cc, src/vmecpp/cpp/vmecpp/vmec/profile_parameterization_data/profile_parameterization_data.h, src/vmecpp/cpp/vmecpp/vmec/pybind11/pybind_vmec.cc, src/vmecpp/cpp/vmecpp/vmec/radial_profiles/radial_profiles.cc, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.h
Modernizes C++ code by adopting standard math constants, using uint8_t for enums, and improving const correctness.
- Replaced manual calculations of mathematical constants with std::numbers (sqrt2, sqrt3, etc.)
- Added explicit uint8_t type to enum classes for memory optimization
- Made member functions const where appropriate
- Changed std::endl to '\n' according to cppcoreguidelines
- Fixed parameter passing to use const references where possible
=> applied clang tidy across codebase

.github/workflows/asan.yaml, .github/workflows/clang_tidy.yaml, .github/workflows/docs.yaml, .github/workflows/test_bazel.yaml, .github/workflows/tests.yaml, README.md, docker/Dockerfile, environment.yml
Replaces all remaining references, to lapacke as it is not available on all systems and vmecpp only depends on lapack after the helpful PR https://github.com/proximafusion/vmecpp/pull/113
=> Replaced remaining lapacke references with lapack

src/vmecpp/cpp/MODULE.bazel
This is part of the effort of migrating all remaining changes from repo to the open source vmecpp
This migrates:
https://github.com/proximafusion/repo/commit/e77cae36f918a0a72315e0b98a5501b7ee7aca00
=> Match bazel version of pybind11 to version in CMakeLists.txt

.github/workflows/pypi_publish.yml, .gitignore, README.md, pyproject.toml
Split the PR https://github.com/proximafusion/vmecpp/pull/143 into smaller contributions.
- Configured cibuildwheel settings in pyproject.toml instead of in the workflow script, so that running `cibuildwheel` locally is more easily reproducible
- Added SDist creation step to the publishing workflow
- Updated README with pip installation instructions
- Added wheelhouse to gitignore
=> Add sdists, moved wheel build settings to .toml so it can be run locally

.github/workflows/tests.yaml, pyproject.toml, src/vmecpp/simsopt_compat.py
Split the PR https://github.com/proximafusion/vmecpp/pull/143 into smaller contributions.
MPI is an optional dependency in simsopt, and we only include it _because of_ simsopt, so it should match the optional behavior.
=> MPI optional

.github/workflows/pypi_publish.yml, .github/workflows/tests.yaml, README.md
Added comprehensive Linux distribution testing to the PyPI publishing workflow.
Added a new job `test-on-different-distros` that tests the built wheels across multiple Linux distributions including the two newest Ubuntu versions, Arch Linux, Debian, Debian:testing and Fedora (the linux distros we discussed). Each distribution is tested both with and without MPI support.
We could add Fedora and Arch installation instructions, since they are tested in CI anyway
https://github.com/proximafusion/vmecpp/actions/runs/13749659177
=> Test wheels on all kinds of linux distros

src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.cc, src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.h, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc
It is not clear to me, why the boundaries object had to be passed to `IdealMhdModel`, if there is a reason feel free to close.
=> Removed unused field from IdealMhdModel

README.md
Feedback from OSSFE was that it's not clear that VmecInput is
a Python object that can be used programmatically: seems to
be tied to the legacy INDATA format.
=> Expand README usage example

tests/test_simsopt_compat.py
I've observed the save function raising an error on HDF5 write. It doesn't seem to happen in CI, but I'll add this regression test once I'm able to reproduce it remotely.
=> Make sure Hdf5 writing doesn't raise an error

src/vmecpp/cpp/vmecpp/simsopt_compat/_fortran_wout_adapter.py, tests/cpp/vmecpp/simsopt_compat/test_fortran_wout_adapter.py
Allow string paths in `FortranWOutAdapter.save()` method to improve API flexibility.
- Modified the `save()` method in `FortranWOutAdapter` to accept both string and Path objects as input
- Added internal conversion of string paths to Path objects
- Updated the method's type hint to reflect this change (`str | Path`)
- Added a parameterized test to verify both string and Path inputs work correctly
This was the only method that didn't accept strings as file paths. It's a common usecase when passing a path directly to write `save("test.h5")` without converting to a Path object before.
=> Support string path in FortranWOutAdapter.save

src/vmecpp/cpp/.bazelrc
We no longer need to disable the warning, because protobuf isn't  a direct dependency any longer.
=> Simplify bazel build, asan works with clang

src/vmecpp/__main__.py
Tiny quality of life improvement imho, if you don't like it feel free too close.
`python src/vmecpp/__main__.py -h`
```log
usage: __main__.py [-h] [-t MAX_THREADS] [-q] [-v] input_file
VMEC++ is a free-boundary ideal-MHD equilibrium solver for stellarators and tokamaks.
positional arguments:
input_file            A VMEC input file either in the classic Fortran 'indata' format or in VMEC++'s JSON format.
options:
-h, --help            show this help message and exit
-t MAX_THREADS, --max-threads MAX_THREADS
Maximum number of threads that VMEC++ should spawn. The actual number might still be lower that this in case there are too few flux
surfaces to keep these many threads busy.
-q, --quiet           If present, silences the printing of VMEC++ logs to standard output.
-v, --version …
```
=> Print version info with help message

.gitignore, pyproject.toml, src/vmecpp/__about__.py
- It was wrapping scikit-build-core anyway, now we have one less dependency
- Hatchling didn't allow editable installs, complicating local Python development without rebuilding the entire source
- the lack of editable installs also caused issues installing `vmecpp` with `uv pip install` 
- Automatically get release version from git tag with `setuptools_scm`  https://setuptools-scm.readthedocs.io/en/stable/usage/
=> Move from hatchling to scikit-build-core

src/vmecpp/simsopt_compat.py, tests/cpp/vmecpp/vmec/pybind11/test_pybind_vmec.py, tests/test_simsopt_compat.py
Refactored the SIMSOPT compatibility layer to use the new Pydantic-based `VmecInput` and `VmecOutput` classes instead of the C++ wrapper classes.
> [!NOTE]
> @eguiraud-pf Does the `vmecpp.VmecWOut` object satisfy all requirements for `Vmec.wout`, or should it be wrapped in the `FortranWOutAdapter`?
This change aligns the SIMSOPT compatibility layer with the vmecpp.run signature.
- Replaced `vmec.VmecINDATAPyWrapper` with `vmecpp.VmecInput` throughout the code
- Updated the `FortranWOutAdapter` usage to directly use `vmecpp.VmecWOut` 
- Modified the `run()` method to accept a `restart_from` parameter instead of `initial_state`
- Updated the parameter types in function signatures to be more explicit
- Fixed the `set_mpol_ntor` method to work with the new Pydantic model by converting to and …
=> simsopt_compat.Vmec should to use Python API instead of CPP API

src/vmecpp/_util.py
&END is not part of the modern Fortran spec, apparently it is a leftover from some older Fortran compilers?
Some tools for parsing Fortran have difficulties with the termination syntax we use, e.g. f90nml which is used in simsopt.
```python
import f90nml
f90nml.read("src/vmecpp/cpp/vmecpp/test_data/input.cth_like_free_bdy")
```
Terminates because the `INDATA` group was closed before. Either / or &END work, but not both. 
I suggest to use the more widespread / syntax for closing. LIBSTELL supports this, simsopt does, and it is standard compliant.
https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2024-2/namelist.html
https://jules-lsm.github.io/latest/namelists/intro.html
=> Terminate Fortran namelist files only with / not / and &END

.github/workflows/tests.yaml, src/vmecpp/_util.py, tests/test_util.py
Fix package resource discovery to support editable installs and add editable install testing to CI.
- Modified the GitHub Actions workflow to test both regular and editable installs by adding a conditional pip install command
- Improved `indata_to_json()` to find the executable using `importlib.metadata.files()` rather than assuming a fixed location relative to the source files, because repo_root broke on editable.
> [!NOTE]
> Required checks are not finishing because the CI test names include editable=true/false due to this change, so they don't match the required check names. Will adjust the required checks once approved.
=> Fully support and test  editable installs

examples/python_api.py, examples/python_api_input.py, examples/simsopt_integration.py, src/vmecpp/__init__.py, src/vmecpp/cpp/vmecpp/common/vmec_indata/vmec_indata.h, src/vmecpp/cpp/vmecpp/vmec/pybind11/pybind_vmec.cc, src/vmecpp/cpp/vmecpp/vmec/pybind11/vmec_indata_pywrapper.cc, src/vmecpp/cpp/vmecpp/vmec/pybind11/vmec_indata_pywrapper.h, src/vmecpp/cpp/vmecpp/vmec/pybind11/vmec_indata_pywrapper_test.cc
Made lasym specific terms std::optional and Optional in Python
https://github.com/proximafusion/vmecpp/pull/198#discussion_r2024553225
> it's a bit weird to say `if not self.lasym`, we don't care about "rbs" and "zbc".
> should we rather say `if self.lasym: # check shapes`, else `# check rbs and zbc are None`?
> At the moment the fields are populated by an empty list when stellarator symmetric! 
> I agree `| None` would be a clearer API, but constitutes a potentially breaking change.
=> Make the stellarator asymetric fields optional in the datamodel

src/vmecpp/simsopt_compat.py
These methods were migrated to vmecpp so we can separate the imports. 
Since a lot of places in repo depend on the old import paths, it might be nice to still keep this around.
=> Keep isvmec and ensure_vmec methods around in simsopt_compat for backwards compatibility

src/vmecpp/__init__.py, tests/test_init.py
Modified the `is_vmec2000_input()` function to properly detect VMEC2000 input files by:
- Skipping blank lines and lines that start with `!` (comments)
Added a regression test using the `input.solovev_analytical` file to verify the fix works with files that have comments before the `&INDATA` marker.
Fixes issue #232 where VMEC2000 input files with comments or blank lines before the `&INDATA` marker were not being correctly identified, causing them to be processed incorrectly.
=> isvmec2000 supports fortran comments and blank lines

src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.cc, src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.h
- string -> filesystem::path to be more expressive
=> mgrid load, string to filesystem

src/vmecpp/__init__.py, tests/test_init.py
Internal API change, doesn't rely on having single element default values set by the CPP API anymore.
=> Explicit default values in aux arrays for wout, robust when passing empty arrays

src/vmecpp/__init__.py
stripping the strings only removed whitespaces, but not zeros, although I believe stripping both should be the correct behavior, instead of making `\x00` a legal value.
=> Zero padded strings are stripped

src/vmecpp/cpp/vmecpp/common/vmec_indata/vmec_indata.cc, src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.cc, src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.h, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.h, tests/test_init.py
The Vmec constructor had absl::CHECK calls in the constructor, which terminated not just the vmecpp execution but also the python wrapper process when mgrid file loading failed, without an Exception or error message that the user could handle. 
Init method for mgrid loading
The PR refactors the `Vmec` constructor to do pure, exception free initialization (Ignoring the possibility of a memory allocation error from std::vector) and moves all sources of exceptions to places where we can report an `absl::Status`. It removes the magnetic response table constructor of Vmec, and all mgrid related initialization is instead handled in `InitMgrid`, a new method that returns the completion status.
**The downside** is, that `Vmec(indata)` does no longer produce a valid object for free-boundary input …
=> mgrid file loading with absl::Status

examples/freeboundary_run_and_hot_restart.py, src/vmecpp/__init__.py, src/vmecpp/cpp/vmecpp/vmec/pybind11/pybind_vmec.cc
The discussed API change for `vmecpp.run()` and a free boundary hot restart example. 
For now using the CPP API for the MagneticFieldResponseTable.
=> Expose FB hot-restart in Python

src/vmecpp/cpp/vmecpp/common/makegrid_lib/BUILD.bazel, src/vmecpp/cpp/vmecpp/common/makegrid_lib/makegrid_lib.cc, src/vmecpp/cpp/vmecpp/common/makegrid_lib/makegrid_lib.h, src/vmecpp/cpp/vmecpp/common/makegrid_lib/makegrid_lib_test.cc, src/vmecpp/cpp/vmecpp/common/util/util.h, src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.cc, src/vmecpp/cpp/vmecpp/vmec/pybind11/pybind_vmec.cc
Make it easier to work with the response table from Python by allowing readwrite and automatic numpy conversion.
- Enables easy integration with Python/simsopt/JAX routines for computing the response table 
- Iterative transition away from stl::vector to Eigen3
Additionally: Move computation of a single coil to a separate function
=> MagneticFieldResponseTable to use Eigen Matrices

src/vmecpp/cpp/vmecpp/common/magnetic_configuration_lib/magnetic_configuration_lib.cc, src/vmecpp/cpp/vmecpp/common/makegrid_lib/makegrid_lib_test.cc
Looking at a few mgrid files, it seems that NUL and NIL are valid values here, could also just check if 'N' is the first character, but this is stricter.
- Check for NIL
- **Report the status if parsing failed and don't silently return an invalid configuration!!!**
- Report status codes in test cases on failiure
=> Raise error if mirror != NIL

src/vmecpp/cpp/MODULE.bazel
The BCR version of Eigen was bumped...
https://registry.bazel.build/modules/eigen/4.0.0-20241125.bcr.1
Apparently Eigen archives on GirLab aren't stable?
https://gitlab.com/libeigen/eigen/-/issues/2919
Current theory by Eigen3 maintainers, is that it is a bug on GitLab side, which caused a bad archive to be cached somewhere...
=> Eigen3.4 version issue with hash in Bazel Central Registry

src/vmecpp/__init__.py, src/vmecpp/_util.py, src/vmecpp/simsopt_compat.py
- By passing a numpy type, it specializes the array types to `npyd.NumpyArray` so type checkers complain less
- Stricter contract, e.g. caught that one wout quantity was parsed to 64bit instead of 32bit int on load (wasn't a problem, but e.g. on save would have been!)
=> More specific array type makes typechecker happy

src/vmecpp/__init__.py, tests/test_init.py
- Added a custom `__init__` method to `VmecInput` class that initializes default values from the C++ `VmecINDATAPyWrapper` class when no arguments are provided
**Pro:** 
- Enables a "pure Python workflow", where the user doesn't have to load any input file. `VmecInput` can be comfortably constructed in a script, without providing explicit defaults for **all quantities**. 
**Con:** 
- Defaults aren't clearly visible for Python users without constructing and inspecting the object.
- only passing a few arguments and defaulting the rest isn't supported, which may be desirable too. 
Alternative: Explicitly default all fields to the same as VmecINDATAPyWrapper
=> Default initializer for VmecInput (reads values from VmecINDATAPyWrapper)

src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.cc, src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.h
Tracking down some undefined behavior and the issues  with even stricter CI checks: 
We were initializing the `fb_[thread_id]` container with nullptr which were stored as a reference in `fb_`.
Although never accessed, invalid references are UB, if it is nullable and non-owning, use a raw pointer.
=> Reference to nullptr in freeb

.github/workflows/asan.yaml, src/vmecpp/cpp/.bazelrc
Added Undefined Behavior Sanitizer (UBSan) to the CI workflow alongside the existing Address Sanitizer (ASan).
https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
I observed rare instances of nan values in output quantities, and wondered if there are remaining undefined behavior/uninitialized memory issues that ASan doesn't detect:
- Integer overflow
- Null pointer dereference
- Using misaligned pointers
- Signed integer overflow
- Array bounds violations
Two minor UB cases were caught (downstack PRs), but mainly this will ensure we don't introduce UB with upstack refactorings.
=> Add ubsan to the CI

src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc
Part of the mission to track down why VMEC++ sometimes doesn't terminate.
The control flow _should_ never reach niterv resets, but this makes it easier to reason that it will definitely terminate.
=> [flow control] Convert while to for loop (num_eqsolve_retries_)

src/vmecpp/cpp/vmecpp/common/magnetic_configuration_lib/magnetic_configuration_lib.cc
To get nice Python exceptions, we need to return meaningful status codes. ☺️
=> Return status code instead of terminating when coils file is missing

pyproject.toml, src/vmecpp/_pydantic_numpy.py, tests/test_pydantic_numpy.py
Added a class to help with serialization and deserialization of classes with numpy arrays annotated with jaxtyping.
Differences to serialization in repo:
- No binary blobs
- Works with `jaxtyping > 0.3.0` by matching on `jt.AbstractArray`
numpydantic is aiming to solve a lot more than we need and caused more issues with the type system than it solved 😥.
Internally we use a different approach, which works nicely. This stripped down version of that library should make integration smoother.
=> BaseModelWithNumpy for numpy+pydantic serialization

.github/workflows/asan.yaml, .github/workflows/clang_tidy.yaml, .github/workflows/pyright.yaml, .github/workflows/test_bazel.yaml, .github/workflows/test_conda_env.yaml, .github/workflows/tests.yaml
Run all CI, even when newer commits are available, so we can always see a green history on main ✔️
=> Don't cancel CI on main

.github/workflows/tests.yaml
Update GitHub Actions test workflow to support multiple Python versions
- Added Python version matrix (3.10, 3.11, 3.12, 3.13) to test across multiple Python versions
- Removed Ubuntu 24.04 from the test matrix, since we are using much fewer system dependencies than before, and the number of spawned CI jobs is already becoming quite large with all the combinations.
- Added pip caching to speed up CI runs
- Removed dependencies that are no longer needed:
- Removed `open-mpi` from default MacOS dependencies
- Removed `libhdf5-dev`, implicitly included in netcdf
A breaking change in 3.13 slipped through, since it wasn't covered by test
=> Python version matrix added to tests

src/vmecpp/__init__.py, src/vmecpp/_util.py, tests/test_init.py
Pydantic provides all kinds of hooks to modify data before serialization and the ability to set a `field_alias`. We combine these features to dump wout files with arbitrary fields, and handle subtle differences betwee `VmecWOut` Python type and the NetCDF type. 
- Special handling (e.g. allow for padding, interpret as int but serialize as float) is done in the pre/post `BeforeValidator` and `PlainSerializer` hooks
- The dimension annotations of the fields == wout dimensions
=> Generalized wout handling, supports arbitrary extra fields now

src/vmecpp/cpp/vmecpp/common/util/util.h, src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.cc, src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.h, src/vmecpp/cpp/vmecpp/vmec/output_quantities/output_quantities.cc, src/vmecpp/cpp/vmecpp/vmec/output_quantities/output_quantities.h, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.h
Replaced integer-based vacuum pressure state tracking with a strongly-typed enum for better clarity.
- Added a new `PlasmaPressureState` enum class to replace the integer-based `ivac` variable
- Defined clear states for vacuum pressure: `OFF`, `INITIALIZED0`, `INITIALIZED`, and `ACTIVE`
- Updated all references to `ivac` throughout the codebase to use the new enum
- Replaced numeric comparisons with explicit enum state checks
=> Converted ivac counter to an enum with descriptive states

src/vmecpp/cpp/vmecpp/common/util/util.h, src/vmecpp/cpp/vmecpp/free_boundary/free_boundary_base/free_boundary_base.h, src/vmecpp/cpp/vmecpp/vmec/handover_storage/handover_storage.h, src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.cc, src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.h, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc, tests/test_free_boundary.py
Usually VMEC turns on the pressure gradually over the first few iterations, to improve robustness. When hot-restarting, we don't want to do that, because the initial guess should already be close to the final solution. Therefore we initialize the vacuum state to `kInitialized` from the beginning, which transitions to `kActive` after the first iteration.
One additional change to the iteration logic is required for everything to work:
The problem is that only the pre-conditioned force-balance includes the vacuum contribution, but the termination criterion (`fsqr<ftol && fsqz<ftol && fsql<ftol`) depends only on the regular, invariant forces. This means a hot-restarted, free-boundary iteration would immediately, if the inner surfaces are in force-balance, eventhough the vacuum force-balance …
=> Skip gradual vacuum pressure activation on hot-restart

AGENTS.md, VMECPP_NAMING_GUIDE.md, examples/compare_vmecpp_to_parvmec.py
Ensure that no non-ASCII characters remain present anywhere in the
VMEC++ source code and adjust the naming guide to make sure the source
tree stays clean in this regard.
=> Remove all non-ASCII characters from VMEC++.

src/vmecpp/cpp/.bazelrc, src/vmecpp/cpp/vmecpp/common/flow_control/flow_control.cc, src/vmecpp/cpp/vmecpp/common/util/util.cc, src/vmecpp/cpp/vmecpp/common/util/util_test.cc, src/vmecpp/cpp/vmecpp/free_boundary/external_magnetic_field/external_magnetic_field.cc, src/vmecpp/cpp/vmecpp/free_boundary/laplace_solver/laplace_solver.cc, src/vmecpp/cpp/vmecpp/free_boundary/mgrid_provider/mgrid_provider.cc, src/vmecpp/cpp/vmecpp/free_boundary/nestor/nestor.cc, src/vmecpp/cpp/vmecpp/free_boundary/singular_integrals/singular_integrals.cc, src/vmecpp/cpp/vmecpp/free_boundary/surface_geometry/surface_geometry.cc, src/vmecpp/cpp/vmecpp/vmec/ideal_mhd_model/ideal_mhd_model.cc, src/vmecpp/cpp/vmecpp/vmec/radial_profiles/radial_profiles.cc, src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc
Allow to build VMEC++ without OpenMP without warnings; needed for Hedron's compile
command extractor, which builds VMEC++ via Bazel.
=> no OpenMP -> no compiler warnings

src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc, tests/test_free_boundary.py
When this wasn't satisfied, vmecpp usually ran into the much scarier error message `IdealMHDModel::update: VAC-VMEC I_TOR MISMATCH : BOUNDARY MAY ENCLOSE EXT. COIL`
which was misleading.
=> Raise on nzeta mismatch in input vs mgrid

examples/fourier_resolution_increase.py
Add an example that showcases how to use VMEC++'s hot-restart feature to incrementally increase the Fourier resolution of a run, similar to the radial resolution increases via `ns_array`.
=> Use hot-restart for Fourier resolution increments.

src/vmecpp/cpp/vmecpp/vmec/vmec/vmec.cc
It is read in each thread in the for loop condition check, but written
only from one thread within SolveEquilibriumLoop.
This PR introduces a barrier to protect the read from liter_flag within
the for loop condition from the write within SolveEquilibriumLoop.
=> Fix a race condition on liter_flag
